[package]
name = "ethereum"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
alloy-primitives = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-trie = { workspace = true }
alloy-serde = { workspace = true }
alloy-rlp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
