[package]
name = "ethereum"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
alloy-primitives = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
